/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BungieNetPlatform.Client.SwaggerDateConverter;

namespace BungieNetPlatform.Model
{
    /// <summary>
    /// Defines Applications.ApplicationScopes
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ApplicationsApplicationScopes
    {
        
		/// <summary>
		/// Read basic user profile information such as the user&#39;s handle, avatar icon, etc.
		/// </summary>
		[EnumMember(Value = "1")]
        ReadBasicUserProfile,
        
		/// <summary>
		/// Read Group/Clan Forums, Wall, and Members for groups and clans that the user has joined.
		/// </summary>
		[EnumMember(Value = "2")]
        ReadGroups,
        
		/// <summary>
		/// Write Group/Clan Forums, Wall, and Members for groups and clans that the user has joined.
		/// </summary>
		[EnumMember(Value = "4")]
        WriteGroups,
        
		/// <summary>
		/// Administer Group/Clan Forums, Wall, and Members for groups and clans that the user is a founder or an administrator.
		/// </summary>
		[EnumMember(Value = "8")]
        AdminGroups,
        
		/// <summary>
		/// Create new groups, clans, and forum posts.
		/// </summary>
		[EnumMember(Value = "16")]
        BnetWrite,
        
		/// <summary>
		/// Move or equip Destiny items
		/// </summary>
		[EnumMember(Value = "32")]
        MoveEquipDestinyItems,
        
		/// <summary>
		/// Read Destiny Inventory and Vault contents.
		/// </summary>
		[EnumMember(Value = "64")]
        ReadDestinyInventoryAndVault,
        
		/// <summary>
		/// Read user data such as who they are web notifications, clan/group memberships, recent activity, muted users.
		/// </summary>
		[EnumMember(Value = "128")]
        ReadUserData,
        
		/// <summary>
		/// Edit user data such as preferred language, status, motto, avatar selection and theme.
		/// </summary>
		[EnumMember(Value = "256")]
        EditUserData,
        
		/// <summary>
		/// Access vendor and advisor data specific to a user.
		/// </summary>
		[EnumMember(Value = "512")]
        ReadDestinyVendorsAndAdvisors,
        
		/// <summary>
		/// Read offer history and claim and apply tokens for the user.
		/// </summary>
		[EnumMember(Value = "1024")]
        ReadAndApplyTokens
    }

}
