/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BungieNetPlatform.Client.SwaggerDateConverter;

namespace BungieNetPlatform.Model
{
    /// <summary>
    /// Defines Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DestinyDefinitionsDestinyTalentNodeStepWeaponPerformances
    {
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "0")]
        None,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "1")]
        RateOfFire,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "2")]
        Damage,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "4")]
        Accuracy,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "8")]
        Range,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "16")]
        Zoom,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "32")]
        Recoil,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "64")]
        Ready,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "128")]
        Reload,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "256")]
        HairTrigger,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "512")]
        AmmoAndMagazine,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "1024")]
        TrackingAndDetonation,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "2048")]
        ShotgunSpread,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "4096")]
        ChargeTime,
        
		/// <summary>
		/// 
		/// </summary>
		[EnumMember(Value = "8191")]
        All
    }

}
