/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyItemTalentGridBlockDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyItemTalentGridBlockDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyItemTalentGridBlockDefinition
        //private DestinyDefinitionsDestinyItemTalentGridBlockDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyItemTalentGridBlockDefinition
            //instance = new DestinyDefinitionsDestinyItemTalentGridBlockDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyItemTalentGridBlockDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyItemTalentGridBlockDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyItemTalentGridBlockDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyItemTalentGridBlockDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyItemTalentGridBlockDefinition");
        }


        /// <summary>
        /// Test the property 'TalentGridHash'
        /// </summary>
        [Test]
        public void TalentGridHashTest()
        {
            // TODO unit test for the property 'TalentGridHash'
        }
        /// <summary>
        /// Test the property 'ItemDetailString'
        /// </summary>
        [Test]
        public void ItemDetailStringTest()
        {
            // TODO unit test for the property 'ItemDetailString'
        }
        /// <summary>
        /// Test the property 'BuildName'
        /// </summary>
        [Test]
        public void BuildNameTest()
        {
            // TODO unit test for the property 'BuildName'
        }
        /// <summary>
        /// Test the property 'HudDamageType'
        /// </summary>
        [Test]
        public void HudDamageTypeTest()
        {
            // TODO unit test for the property 'HudDamageType'
        }
        /// <summary>
        /// Test the property 'HudIcon'
        /// </summary>
        [Test]
        public void HudIconTest()
        {
            // TODO unit test for the property 'HudIcon'
        }

    }

}
