/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDirectorDestinyActivityGraphDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDirectorDestinyActivityGraphDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDirectorDestinyActivityGraphDefinition
        //private DestinyDefinitionsDirectorDestinyActivityGraphDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDirectorDestinyActivityGraphDefinition
            //instance = new DestinyDefinitionsDirectorDestinyActivityGraphDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDirectorDestinyActivityGraphDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDirectorDestinyActivityGraphDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDirectorDestinyActivityGraphDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDirectorDestinyActivityGraphDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDirectorDestinyActivityGraphDefinition");
        }


        /// <summary>
        /// Test the property 'Nodes'
        /// </summary>
        [Test]
        public void NodesTest()
        {
            // TODO unit test for the property 'Nodes'
        }
        /// <summary>
        /// Test the property 'ArtElements'
        /// </summary>
        [Test]
        public void ArtElementsTest()
        {
            // TODO unit test for the property 'ArtElements'
        }
        /// <summary>
        /// Test the property 'Connections'
        /// </summary>
        [Test]
        public void ConnectionsTest()
        {
            // TODO unit test for the property 'Connections'
        }
        /// <summary>
        /// Test the property 'DisplayObjectives'
        /// </summary>
        [Test]
        public void DisplayObjectivesTest()
        {
            // TODO unit test for the property 'DisplayObjectives'
        }
        /// <summary>
        /// Test the property 'DisplayProgressions'
        /// </summary>
        [Test]
        public void DisplayProgressionsTest()
        {
            // TODO unit test for the property 'DisplayProgressions'
        }
        /// <summary>
        /// Test the property 'LinkedGraphs'
        /// </summary>
        [Test]
        public void LinkedGraphsTest()
        {
            // TODO unit test for the property 'LinkedGraphs'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Test]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }

    }

}
