/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyVendorItemDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyVendorItemDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyVendorItemDefinition
        //private DestinyDefinitionsDestinyVendorItemDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyVendorItemDefinition
            //instance = new DestinyDefinitionsDestinyVendorItemDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyVendorItemDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyVendorItemDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyVendorItemDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyVendorItemDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyVendorItemDefinition");
        }


        /// <summary>
        /// Test the property 'VendorItemIndex'
        /// </summary>
        [Test]
        public void VendorItemIndexTest()
        {
            // TODO unit test for the property 'VendorItemIndex'
        }
        /// <summary>
        /// Test the property 'ItemHash'
        /// </summary>
        [Test]
        public void ItemHashTest()
        {
            // TODO unit test for the property 'ItemHash'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'FailureIndexes'
        /// </summary>
        [Test]
        public void FailureIndexesTest()
        {
            // TODO unit test for the property 'FailureIndexes'
        }
        /// <summary>
        /// Test the property 'Currencies'
        /// </summary>
        [Test]
        public void CurrenciesTest()
        {
            // TODO unit test for the property 'Currencies'
        }
        /// <summary>
        /// Test the property 'RefundPolicy'
        /// </summary>
        [Test]
        public void RefundPolicyTest()
        {
            // TODO unit test for the property 'RefundPolicy'
        }
        /// <summary>
        /// Test the property 'RefundTimeLimit'
        /// </summary>
        [Test]
        public void RefundTimeLimitTest()
        {
            // TODO unit test for the property 'RefundTimeLimit'
        }
        /// <summary>
        /// Test the property 'CreationLevels'
        /// </summary>
        [Test]
        public void CreationLevelsTest()
        {
            // TODO unit test for the property 'CreationLevels'
        }
        /// <summary>
        /// Test the property 'DisplayCategoryIndex'
        /// </summary>
        [Test]
        public void DisplayCategoryIndexTest()
        {
            // TODO unit test for the property 'DisplayCategoryIndex'
        }
        /// <summary>
        /// Test the property 'CategoryIndex'
        /// </summary>
        [Test]
        public void CategoryIndexTest()
        {
            // TODO unit test for the property 'CategoryIndex'
        }
        /// <summary>
        /// Test the property 'OriginalCategoryIndex'
        /// </summary>
        [Test]
        public void OriginalCategoryIndexTest()
        {
            // TODO unit test for the property 'OriginalCategoryIndex'
        }
        /// <summary>
        /// Test the property 'MinimumLevel'
        /// </summary>
        [Test]
        public void MinimumLevelTest()
        {
            // TODO unit test for the property 'MinimumLevel'
        }
        /// <summary>
        /// Test the property 'MaximumLevel'
        /// </summary>
        [Test]
        public void MaximumLevelTest()
        {
            // TODO unit test for the property 'MaximumLevel'
        }
        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Test]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'DisplayCategory'
        /// </summary>
        [Test]
        public void DisplayCategoryTest()
        {
            // TODO unit test for the property 'DisplayCategory'
        }
        /// <summary>
        /// Test the property 'InventoryBucketHash'
        /// </summary>
        [Test]
        public void InventoryBucketHashTest()
        {
            // TODO unit test for the property 'InventoryBucketHash'
        }
        /// <summary>
        /// Test the property 'VisibilityScope'
        /// </summary>
        [Test]
        public void VisibilityScopeTest()
        {
            // TODO unit test for the property 'VisibilityScope'
        }
        /// <summary>
        /// Test the property 'PurchasableScope'
        /// </summary>
        [Test]
        public void PurchasableScopeTest()
        {
            // TODO unit test for the property 'PurchasableScope'
        }

    }

}
