/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyHistoricalStatsDefinitionsPeriodType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyHistoricalStatsDefinitionsPeriodTypeTests
    {
        // TODO uncomment below to declare an instance variable for DestinyHistoricalStatsDefinitionsPeriodType
        //private DestinyHistoricalStatsDefinitionsPeriodType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyHistoricalStatsDefinitionsPeriodType
            //instance = new DestinyHistoricalStatsDefinitionsPeriodType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyHistoricalStatsDefinitionsPeriodType
        /// </summary>
        [Test]
        public void DestinyHistoricalStatsDefinitionsPeriodTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyHistoricalStatsDefinitionsPeriodType
            //Assert.IsInstanceOfType<DestinyHistoricalStatsDefinitionsPeriodType> (instance, "variable 'instance' is a DestinyHistoricalStatsDefinitionsPeriodType");
        }



    }

}
