/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinySandboxPerkDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinySandboxPerkDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinySandboxPerkDefinition
        //private DestinyDefinitionsDestinySandboxPerkDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinySandboxPerkDefinition
            //instance = new DestinyDefinitionsDestinySandboxPerkDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinySandboxPerkDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinySandboxPerkDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinySandboxPerkDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinySandboxPerkDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinySandboxPerkDefinition");
        }


        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Test]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }
        /// <summary>
        /// Test the property 'PerkIdentifier'
        /// </summary>
        [Test]
        public void PerkIdentifierTest()
        {
            // TODO unit test for the property 'PerkIdentifier'
        }
        /// <summary>
        /// Test the property 'IsDisplayable'
        /// </summary>
        [Test]
        public void IsDisplayableTest()
        {
            // TODO unit test for the property 'IsDisplayable'
        }
        /// <summary>
        /// Test the property 'DamageType'
        /// </summary>
        [Test]
        public void DamageTypeTest()
        {
            // TODO unit test for the property 'DamageType'
        }
        /// <summary>
        /// Test the property 'DamageTypeHash'
        /// </summary>
        [Test]
        public void DamageTypeHashTest()
        {
            // TODO unit test for the property 'DamageTypeHash'
        }
        /// <summary>
        /// Test the property 'PerkGroups'
        /// </summary>
        [Test]
        public void PerkGroupsTest()
        {
            // TODO unit test for the property 'PerkGroups'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Test]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }

    }

}
