/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyEntitySearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyEntitySearchResultTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyEntitySearchResult
        //private DestinyDefinitionsDestinyEntitySearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyEntitySearchResult
            //instance = new DestinyDefinitionsDestinyEntitySearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyEntitySearchResult
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyEntitySearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyEntitySearchResult
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyEntitySearchResult> (instance, "variable 'instance' is a DestinyDefinitionsDestinyEntitySearchResult");
        }


        /// <summary>
        /// Test the property 'SuggestedWords'
        /// </summary>
        [Test]
        public void SuggestedWordsTest()
        {
            // TODO unit test for the property 'SuggestedWords'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
