/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyVendorDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyVendorDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyVendorDefinition
        //private DestinyDefinitionsDestinyVendorDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyVendorDefinition
            //instance = new DestinyDefinitionsDestinyVendorDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyVendorDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyVendorDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyVendorDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyVendorDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyVendorDefinition");
        }


        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Test]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }
        /// <summary>
        /// Test the property 'BuyString'
        /// </summary>
        [Test]
        public void BuyStringTest()
        {
            // TODO unit test for the property 'BuyString'
        }
        /// <summary>
        /// Test the property 'SellString'
        /// </summary>
        [Test]
        public void SellStringTest()
        {
            // TODO unit test for the property 'SellString'
        }
        /// <summary>
        /// Test the property 'DisplayItemHash'
        /// </summary>
        [Test]
        public void DisplayItemHashTest()
        {
            // TODO unit test for the property 'DisplayItemHash'
        }
        /// <summary>
        /// Test the property 'InhibitBuying'
        /// </summary>
        [Test]
        public void InhibitBuyingTest()
        {
            // TODO unit test for the property 'InhibitBuying'
        }
        /// <summary>
        /// Test the property 'InhibitSelling'
        /// </summary>
        [Test]
        public void InhibitSellingTest()
        {
            // TODO unit test for the property 'InhibitSelling'
        }
        /// <summary>
        /// Test the property 'FactionHash'
        /// </summary>
        [Test]
        public void FactionHashTest()
        {
            // TODO unit test for the property 'FactionHash'
        }
        /// <summary>
        /// Test the property 'ResetIntervalMinutes'
        /// </summary>
        [Test]
        public void ResetIntervalMinutesTest()
        {
            // TODO unit test for the property 'ResetIntervalMinutes'
        }
        /// <summary>
        /// Test the property 'ResetOffsetMinutes'
        /// </summary>
        [Test]
        public void ResetOffsetMinutesTest()
        {
            // TODO unit test for the property 'ResetOffsetMinutes'
        }
        /// <summary>
        /// Test the property 'FailureStrings'
        /// </summary>
        [Test]
        public void FailureStringsTest()
        {
            // TODO unit test for the property 'FailureStrings'
        }
        /// <summary>
        /// Test the property 'UnlockRanges'
        /// </summary>
        [Test]
        public void UnlockRangesTest()
        {
            // TODO unit test for the property 'UnlockRanges'
        }
        /// <summary>
        /// Test the property 'VendorIdentifier'
        /// </summary>
        [Test]
        public void VendorIdentifierTest()
        {
            // TODO unit test for the property 'VendorIdentifier'
        }
        /// <summary>
        /// Test the property 'VendorPortrait'
        /// </summary>
        [Test]
        public void VendorPortraitTest()
        {
            // TODO unit test for the property 'VendorPortrait'
        }
        /// <summary>
        /// Test the property 'VendorBanner'
        /// </summary>
        [Test]
        public void VendorBannerTest()
        {
            // TODO unit test for the property 'VendorBanner'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'Visible'
        /// </summary>
        [Test]
        public void VisibleTest()
        {
            // TODO unit test for the property 'Visible'
        }
        /// <summary>
        /// Test the property 'VendorCategoryIdentifier'
        /// </summary>
        [Test]
        public void VendorCategoryIdentifierTest()
        {
            // TODO unit test for the property 'VendorCategoryIdentifier'
        }
        /// <summary>
        /// Test the property 'VendorSubcategoryIdentifier'
        /// </summary>
        [Test]
        public void VendorSubcategoryIdentifierTest()
        {
            // TODO unit test for the property 'VendorSubcategoryIdentifier'
        }
        /// <summary>
        /// Test the property 'ConsolidateCategories'
        /// </summary>
        [Test]
        public void ConsolidateCategoriesTest()
        {
            // TODO unit test for the property 'ConsolidateCategories'
        }
        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Test]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Test]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'OriginalCategories'
        /// </summary>
        [Test]
        public void OriginalCategoriesTest()
        {
            // TODO unit test for the property 'OriginalCategories'
        }
        /// <summary>
        /// Test the property 'DisplayCategories'
        /// </summary>
        [Test]
        public void DisplayCategoriesTest()
        {
            // TODO unit test for the property 'DisplayCategories'
        }
        /// <summary>
        /// Test the property 'Interactions'
        /// </summary>
        [Test]
        public void InteractionsTest()
        {
            // TODO unit test for the property 'Interactions'
        }
        /// <summary>
        /// Test the property 'InventoryFlyouts'
        /// </summary>
        [Test]
        public void InventoryFlyoutsTest()
        {
            // TODO unit test for the property 'InventoryFlyouts'
        }
        /// <summary>
        /// Test the property 'ItemList'
        /// </summary>
        [Test]
        public void ItemListTest()
        {
            // TODO unit test for the property 'ItemList'
        }
        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Test]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }
        /// <summary>
        /// Test the property 'AcceptedItems'
        /// </summary>
        [Test]
        public void AcceptedItemsTest()
        {
            // TODO unit test for the property 'AcceptedItems'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Test]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }

    }

}
