/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyVendorInteractionDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyVendorInteractionDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyVendorInteractionDefinition
        //private DestinyDefinitionsDestinyVendorInteractionDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyVendorInteractionDefinition
            //instance = new DestinyDefinitionsDestinyVendorInteractionDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyVendorInteractionDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyVendorInteractionDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyVendorInteractionDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyVendorInteractionDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyVendorInteractionDefinition");
        }


        /// <summary>
        /// Test the property 'Replies'
        /// </summary>
        [Test]
        public void RepliesTest()
        {
            // TODO unit test for the property 'Replies'
        }
        /// <summary>
        /// Test the property 'VendorCategoryIndex'
        /// </summary>
        [Test]
        public void VendorCategoryIndexTest()
        {
            // TODO unit test for the property 'VendorCategoryIndex'
        }
        /// <summary>
        /// Test the property 'QuestlineItemHash'
        /// </summary>
        [Test]
        public void QuestlineItemHashTest()
        {
            // TODO unit test for the property 'QuestlineItemHash'
        }
        /// <summary>
        /// Test the property 'SackInteractionList'
        /// </summary>
        [Test]
        public void SackInteractionListTest()
        {
            // TODO unit test for the property 'SackInteractionList'
        }
        /// <summary>
        /// Test the property 'UiInteractionType'
        /// </summary>
        [Test]
        public void UiInteractionTypeTest()
        {
            // TODO unit test for the property 'UiInteractionType'
        }
        /// <summary>
        /// Test the property 'RewardBlockLabel'
        /// </summary>
        [Test]
        public void RewardBlockLabelTest()
        {
            // TODO unit test for the property 'RewardBlockLabel'
        }
        /// <summary>
        /// Test the property 'RewardVendorCategoryIndex'
        /// </summary>
        [Test]
        public void RewardVendorCategoryIndexTest()
        {
            // TODO unit test for the property 'RewardVendorCategoryIndex'
        }
        /// <summary>
        /// Test the property 'FlavorLineOne'
        /// </summary>
        [Test]
        public void FlavorLineOneTest()
        {
            // TODO unit test for the property 'FlavorLineOne'
        }
        /// <summary>
        /// Test the property 'FlavorLineTwo'
        /// </summary>
        [Test]
        public void FlavorLineTwoTest()
        {
            // TODO unit test for the property 'FlavorLineTwo'
        }
        /// <summary>
        /// Test the property 'HeaderDisplayProperties'
        /// </summary>
        [Test]
        public void HeaderDisplayPropertiesTest()
        {
            // TODO unit test for the property 'HeaderDisplayProperties'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Test]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }

    }

}
