/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DictionaryComponentResponseOfuint32AndDestinyItemPlugComponentTests
    {
        // TODO uncomment below to declare an instance variable for DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent
        //private DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent
            //instance = new DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent
        /// </summary>
        [Test]
        public void DictionaryComponentResponseOfuint32AndDestinyItemPlugComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent
            //Assert.IsInstanceOfType<DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent> (instance, "variable 'instance' is a DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Privacy'
        /// </summary>
        [Test]
        public void PrivacyTest()
        {
            // TODO unit test for the property 'Privacy'
        }

    }

}
