/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing ForumPollResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ForumPollResponseTests
    {
        // TODO uncomment below to declare an instance variable for ForumPollResponse
        //private ForumPollResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForumPollResponse
            //instance = new ForumPollResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForumPollResponse
        /// </summary>
        [Test]
        public void ForumPollResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForumPollResponse
            //Assert.IsInstanceOfType<ForumPollResponse> (instance, "variable 'instance' is a ForumPollResponse");
        }


        /// <summary>
        /// Test the property 'TopicId'
        /// </summary>
        [Test]
        public void TopicIdTest()
        {
            // TODO unit test for the property 'TopicId'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'TotalVotes'
        /// </summary>
        [Test]
        public void TotalVotesTest()
        {
            // TODO unit test for the property 'TotalVotes'
        }

    }

}
