/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing GroupsV2GroupMembership
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupsV2GroupMembershipTests
    {
        // TODO uncomment below to declare an instance variable for GroupsV2GroupMembership
        //private GroupsV2GroupMembership instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupsV2GroupMembership
            //instance = new GroupsV2GroupMembership();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupsV2GroupMembership
        /// </summary>
        [Test]
        public void GroupsV2GroupMembershipInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupsV2GroupMembership
            //Assert.IsInstanceOfType<GroupsV2GroupMembership> (instance, "variable 'instance' is a GroupsV2GroupMembership");
        }


        /// <summary>
        /// Test the property 'Member'
        /// </summary>
        [Test]
        public void MemberTest()
        {
            // TODO unit test for the property 'Member'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

    }

}
