/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing GroupsV2GroupPotentialMemberStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupsV2GroupPotentialMemberStatusTests
    {
        // TODO uncomment below to declare an instance variable for GroupsV2GroupPotentialMemberStatus
        //private GroupsV2GroupPotentialMemberStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupsV2GroupPotentialMemberStatus
            //instance = new GroupsV2GroupPotentialMemberStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupsV2GroupPotentialMemberStatus
        /// </summary>
        [Test]
        public void GroupsV2GroupPotentialMemberStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupsV2GroupPotentialMemberStatus
            //Assert.IsInstanceOfType<GroupsV2GroupPotentialMemberStatus> (instance, "variable 'instance' is a GroupsV2GroupPotentialMemberStatus");
        }



    }

}
