/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing GroupsV2GroupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupsV2GroupResponseTests
    {
        // TODO uncomment below to declare an instance variable for GroupsV2GroupResponse
        //private GroupsV2GroupResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupsV2GroupResponse
            //instance = new GroupsV2GroupResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupsV2GroupResponse
        /// </summary>
        [Test]
        public void GroupsV2GroupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupsV2GroupResponse
            //Assert.IsInstanceOfType<GroupsV2GroupResponse> (instance, "variable 'instance' is a GroupsV2GroupResponse");
        }


        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Test]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }
        /// <summary>
        /// Test the property 'Founder'
        /// </summary>
        [Test]
        public void FounderTest()
        {
            // TODO unit test for the property 'Founder'
        }
        /// <summary>
        /// Test the property 'AlliedIds'
        /// </summary>
        [Test]
        public void AlliedIdsTest()
        {
            // TODO unit test for the property 'AlliedIds'
        }
        /// <summary>
        /// Test the property 'ParentGroup'
        /// </summary>
        [Test]
        public void ParentGroupTest()
        {
            // TODO unit test for the property 'ParentGroup'
        }
        /// <summary>
        /// Test the property 'AllianceStatus'
        /// </summary>
        [Test]
        public void AllianceStatusTest()
        {
            // TODO unit test for the property 'AllianceStatus'
        }
        /// <summary>
        /// Test the property 'GroupJoinInviteCount'
        /// </summary>
        [Test]
        public void GroupJoinInviteCountTest()
        {
            // TODO unit test for the property 'GroupJoinInviteCount'
        }
        /// <summary>
        /// Test the property 'CurrentUserMemberMap'
        /// </summary>
        [Test]
        public void CurrentUserMemberMapTest()
        {
            // TODO unit test for the property 'CurrentUserMemberMap'
        }
        /// <summary>
        /// Test the property 'CurrentUserPotentialMemberMap'
        /// </summary>
        [Test]
        public void CurrentUserPotentialMemberMapTest()
        {
            // TODO unit test for the property 'CurrentUserPotentialMemberMap'
        }

    }

}
