/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.BungieNetPlatform.Api;
using BungieNetPlatform.BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing GroupsV2GroupV2Card
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupsV2GroupV2CardTests
    {
        // TODO uncomment below to declare an instance variable for GroupsV2GroupV2Card
        //private GroupsV2GroupV2Card instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupsV2GroupV2Card
            //instance = new GroupsV2GroupV2Card();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupsV2GroupV2Card
        /// </summary>
        [Test]
        public void GroupsV2GroupV2CardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupsV2GroupV2Card
            //Assert.IsInstanceOfType<GroupsV2GroupV2Card> (instance, "variable 'instance' is a GroupsV2GroupV2Card");
        }


        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Test]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'GroupType'
        /// </summary>
        [Test]
        public void GroupTypeTest()
        {
            // TODO unit test for the property 'GroupType'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Test]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'About'
        /// </summary>
        [Test]
        public void AboutTest()
        {
            // TODO unit test for the property 'About'
        }
        /// <summary>
        /// Test the property 'Motto'
        /// </summary>
        [Test]
        public void MottoTest()
        {
            // TODO unit test for the property 'Motto'
        }
        /// <summary>
        /// Test the property 'MemberCount'
        /// </summary>
        [Test]
        public void MemberCountTest()
        {
            // TODO unit test for the property 'MemberCount'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Test]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
        /// <summary>
        /// Test the property 'MembershipOption'
        /// </summary>
        [Test]
        public void MembershipOptionTest()
        {
            // TODO unit test for the property 'MembershipOption'
        }
        /// <summary>
        /// Test the property 'Capabilities'
        /// </summary>
        [Test]
        public void CapabilitiesTest()
        {
            // TODO unit test for the property 'Capabilities'
        }
        /// <summary>
        /// Test the property 'ClanInfo'
        /// </summary>
        [Test]
        public void ClanInfoTest()
        {
            // TODO unit test for the property 'ClanInfo'
        }
        /// <summary>
        /// Test the property 'AvatarPath'
        /// </summary>
        [Test]
        public void AvatarPathTest()
        {
            // TODO unit test for the property 'AvatarPath'
        }
        /// <summary>
        /// Test the property 'Theme'
        /// </summary>
        [Test]
        public void ThemeTest()
        {
            // TODO unit test for the property 'Theme'
        }

    }

}
