/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyEntitiesItemsDestinyItemTalentGridComponent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyEntitiesItemsDestinyItemTalentGridComponentTests
    {
        // TODO uncomment below to declare an instance variable for DestinyEntitiesItemsDestinyItemTalentGridComponent
        //private DestinyEntitiesItemsDestinyItemTalentGridComponent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyEntitiesItemsDestinyItemTalentGridComponent
            //instance = new DestinyEntitiesItemsDestinyItemTalentGridComponent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyEntitiesItemsDestinyItemTalentGridComponent
        /// </summary>
        [Test]
        public void DestinyEntitiesItemsDestinyItemTalentGridComponentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyEntitiesItemsDestinyItemTalentGridComponent
            //Assert.IsInstanceOfType<DestinyEntitiesItemsDestinyItemTalentGridComponent> (instance, "variable 'instance' is a DestinyEntitiesItemsDestinyItemTalentGridComponent");
        }


        /// <summary>
        /// Test the property 'TalentGridHash'
        /// </summary>
        [Test]
        public void TalentGridHashTest()
        {
            // TODO unit test for the property 'TalentGridHash'
        }
        /// <summary>
        /// Test the property 'Nodes'
        /// </summary>
        [Test]
        public void NodesTest()
        {
            // TODO unit test for the property 'Nodes'
        }
        /// <summary>
        /// Test the property 'IsGridComplete'
        /// </summary>
        [Test]
        public void IsGridCompleteTest()
        {
            // TODO unit test for the property 'IsGridComplete'
        }
        /// <summary>
        /// Test the property 'GridProgression'
        /// </summary>
        [Test]
        public void GridProgressionTest()
        {
            // TODO unit test for the property 'GridProgression'
        }

    }

}
