/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsItemsDestinyPlugRuleDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsItemsDestinyPlugRuleDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsItemsDestinyPlugRuleDefinition
        //private DestinyDefinitionsItemsDestinyPlugRuleDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsItemsDestinyPlugRuleDefinition
            //instance = new DestinyDefinitionsItemsDestinyPlugRuleDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsItemsDestinyPlugRuleDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsItemsDestinyPlugRuleDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsItemsDestinyPlugRuleDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsItemsDestinyPlugRuleDefinition> (instance, "variable 'instance' is a DestinyDefinitionsItemsDestinyPlugRuleDefinition");
        }


        /// <summary>
        /// Test the property 'FailureMessage'
        /// </summary>
        [Test]
        public void FailureMessageTest()
        {
            // TODO unit test for the property 'FailureMessage'
        }

    }

}
