/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyItemValueBlockDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyItemValueBlockDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyItemValueBlockDefinition
        //private DestinyDefinitionsDestinyItemValueBlockDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyItemValueBlockDefinition
            //instance = new DestinyDefinitionsDestinyItemValueBlockDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyItemValueBlockDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyItemValueBlockDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyItemValueBlockDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyItemValueBlockDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyItemValueBlockDefinition");
        }


        /// <summary>
        /// Test the property 'ItemValue'
        /// </summary>
        [Test]
        public void ItemValueTest()
        {
            // TODO unit test for the property 'ItemValue'
        }
        /// <summary>
        /// Test the property 'ValueDescription'
        /// </summary>
        [Test]
        public void ValueDescriptionTest()
        {
            // TODO unit test for the property 'ValueDescription'
        }

    }

}
