/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyTransferStatuses
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyTransferStatusesTests
    {
        // TODO uncomment below to declare an instance variable for DestinyTransferStatuses
        //private DestinyTransferStatuses instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyTransferStatuses
            //instance = new DestinyTransferStatuses();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyTransferStatuses
        /// </summary>
        [Test]
        public void DestinyTransferStatusesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyTransferStatuses
            //Assert.IsInstanceOfType<DestinyTransferStatuses> (instance, "variable 'instance' is a DestinyTransferStatuses");
        }



    }

}
