/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyItemInventoryBlockDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyItemInventoryBlockDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyItemInventoryBlockDefinition
        //private DestinyDefinitionsDestinyItemInventoryBlockDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyItemInventoryBlockDefinition
            //instance = new DestinyDefinitionsDestinyItemInventoryBlockDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyItemInventoryBlockDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyItemInventoryBlockDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyItemInventoryBlockDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyItemInventoryBlockDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyItemInventoryBlockDefinition");
        }


        /// <summary>
        /// Test the property 'StackUniqueLabel'
        /// </summary>
        [Test]
        public void StackUniqueLabelTest()
        {
            // TODO unit test for the property 'StackUniqueLabel'
        }
        /// <summary>
        /// Test the property 'MaxStackSize'
        /// </summary>
        [Test]
        public void MaxStackSizeTest()
        {
            // TODO unit test for the property 'MaxStackSize'
        }
        /// <summary>
        /// Test the property 'BucketTypeHash'
        /// </summary>
        [Test]
        public void BucketTypeHashTest()
        {
            // TODO unit test for the property 'BucketTypeHash'
        }
        /// <summary>
        /// Test the property 'RecoveryBucketTypeHash'
        /// </summary>
        [Test]
        public void RecoveryBucketTypeHashTest()
        {
            // TODO unit test for the property 'RecoveryBucketTypeHash'
        }
        /// <summary>
        /// Test the property 'TierTypeHash'
        /// </summary>
        [Test]
        public void TierTypeHashTest()
        {
            // TODO unit test for the property 'TierTypeHash'
        }
        /// <summary>
        /// Test the property 'IsInstanceItem'
        /// </summary>
        [Test]
        public void IsInstanceItemTest()
        {
            // TODO unit test for the property 'IsInstanceItem'
        }
        /// <summary>
        /// Test the property 'TierTypeName'
        /// </summary>
        [Test]
        public void TierTypeNameTest()
        {
            // TODO unit test for the property 'TierTypeName'
        }
        /// <summary>
        /// Test the property 'TierType'
        /// </summary>
        [Test]
        public void TierTypeTest()
        {
            // TODO unit test for the property 'TierType'
        }

    }

}
