/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyConfigDestinyManifest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyConfigDestinyManifestTests
    {
        // TODO uncomment below to declare an instance variable for DestinyConfigDestinyManifest
        //private DestinyConfigDestinyManifest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyConfigDestinyManifest
            //instance = new DestinyConfigDestinyManifest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyConfigDestinyManifest
        /// </summary>
        [Test]
        public void DestinyConfigDestinyManifestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyConfigDestinyManifest
            //Assert.IsInstanceOfType<DestinyConfigDestinyManifest> (instance, "variable 'instance' is a DestinyConfigDestinyManifest");
        }


        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'MobileAssetContentPath'
        /// </summary>
        [Test]
        public void MobileAssetContentPathTest()
        {
            // TODO unit test for the property 'MobileAssetContentPath'
        }
        /// <summary>
        /// Test the property 'MobileGearAssetDataBases'
        /// </summary>
        [Test]
        public void MobileGearAssetDataBasesTest()
        {
            // TODO unit test for the property 'MobileGearAssetDataBases'
        }
        /// <summary>
        /// Test the property 'MobileWorldContentPaths'
        /// </summary>
        [Test]
        public void MobileWorldContentPathsTest()
        {
            // TODO unit test for the property 'MobileWorldContentPaths'
        }
        /// <summary>
        /// Test the property 'MobileClanBannerDatabasePath'
        /// </summary>
        [Test]
        public void MobileClanBannerDatabasePathTest()
        {
            // TODO unit test for the property 'MobileClanBannerDatabasePath'
        }
        /// <summary>
        /// Test the property 'MobileGearCDN'
        /// </summary>
        [Test]
        public void MobileGearCDNTest()
        {
            // TODO unit test for the property 'MobileGearCDN'
        }

    }

}
