/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyItemSetBlockEntryDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyItemSetBlockEntryDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyItemSetBlockEntryDefinition
        //private DestinyDefinitionsDestinyItemSetBlockEntryDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyItemSetBlockEntryDefinition
            //instance = new DestinyDefinitionsDestinyItemSetBlockEntryDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyItemSetBlockEntryDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyItemSetBlockEntryDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyItemSetBlockEntryDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyItemSetBlockEntryDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyItemSetBlockEntryDefinition");
        }


        /// <summary>
        /// Test the property 'TrackingValue'
        /// </summary>
        [Test]
        public void TrackingValueTest()
        {
            // TODO unit test for the property 'TrackingValue'
        }
        /// <summary>
        /// Test the property 'ItemHash'
        /// </summary>
        [Test]
        public void ItemHashTest()
        {
            // TODO unit test for the property 'ItemHash'
        }

    }

}
