/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItemTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem
        //private DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem
            //instance = new DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem
        /// </summary>
        [Test]
        public void DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem
            //Assert.IsInstanceOfType<DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem> (instance, "variable 'instance' is a DestinyDefinitionsMilestonesDestinyMilestoneQuestRewardItem");
        }


        /// <summary>
        /// Test the property 'VendorHash'
        /// </summary>
        [Test]
        public void VendorHashTest()
        {
            // TODO unit test for the property 'VendorHash'
        }
        /// <summary>
        /// Test the property 'VendorItemIndex'
        /// </summary>
        [Test]
        public void VendorItemIndexTest()
        {
            // TODO unit test for the property 'VendorItemIndex'
        }
        /// <summary>
        /// Test the property 'ItemHash'
        /// </summary>
        [Test]
        public void ItemHashTest()
        {
            // TODO unit test for the property 'ItemHash'
        }
        /// <summary>
        /// Test the property 'ItemInstanceId'
        /// </summary>
        [Test]
        public void ItemInstanceIdTest()
        {
            // TODO unit test for the property 'ItemInstanceId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
