/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyHistoricalStatsDestinyHistoricalStatsAccountResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyHistoricalStatsDestinyHistoricalStatsAccountResultTests
    {
        // TODO uncomment below to declare an instance variable for DestinyHistoricalStatsDestinyHistoricalStatsAccountResult
        //private DestinyHistoricalStatsDestinyHistoricalStatsAccountResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyHistoricalStatsDestinyHistoricalStatsAccountResult
            //instance = new DestinyHistoricalStatsDestinyHistoricalStatsAccountResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyHistoricalStatsDestinyHistoricalStatsAccountResult
        /// </summary>
        [Test]
        public void DestinyHistoricalStatsDestinyHistoricalStatsAccountResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyHistoricalStatsDestinyHistoricalStatsAccountResult
            //Assert.IsInstanceOfType<DestinyHistoricalStatsDestinyHistoricalStatsAccountResult> (instance, "variable 'instance' is a DestinyHistoricalStatsDestinyHistoricalStatsAccountResult");
        }


        /// <summary>
        /// Test the property 'MergedDeletedCharacters'
        /// </summary>
        [Test]
        public void MergedDeletedCharactersTest()
        {
            // TODO unit test for the property 'MergedDeletedCharacters'
        }
        /// <summary>
        /// Test the property 'MergedAllCharacters'
        /// </summary>
        [Test]
        public void MergedAllCharactersTest()
        {
            // TODO unit test for the property 'MergedAllCharacters'
        }
        /// <summary>
        /// Test the property 'Characters'
        /// </summary>
        [Test]
        public void CharactersTest()
        {
            // TODO unit test for the property 'Characters'
        }

    }

}
