/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyVendorActionDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyVendorActionDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyVendorActionDefinition
        //private DestinyDefinitionsDestinyVendorActionDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyVendorActionDefinition
            //instance = new DestinyDefinitionsDestinyVendorActionDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyVendorActionDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyVendorActionDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyVendorActionDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyVendorActionDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyVendorActionDefinition");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ExecuteSeconds'
        /// </summary>
        [Test]
        public void ExecuteSecondsTest()
        {
            // TODO unit test for the property 'ExecuteSeconds'
        }
        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Test]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Verb'
        /// </summary>
        [Test]
        public void VerbTest()
        {
            // TODO unit test for the property 'Verb'
        }
        /// <summary>
        /// Test the property 'IsPositive'
        /// </summary>
        [Test]
        public void IsPositiveTest()
        {
            // TODO unit test for the property 'IsPositive'
        }
        /// <summary>
        /// Test the property 'ActionId'
        /// </summary>
        [Test]
        public void ActionIdTest()
        {
            // TODO unit test for the property 'ActionId'
        }
        /// <summary>
        /// Test the property 'ActionHash'
        /// </summary>
        [Test]
        public void ActionHashTest()
        {
            // TODO unit test for the property 'ActionHash'
        }
        /// <summary>
        /// Test the property 'AutoPerformAction'
        /// </summary>
        [Test]
        public void AutoPerformActionTest()
        {
            // TODO unit test for the property 'AutoPerformAction'
        }

    }

}
