/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyItemCategoryDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyItemCategoryDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyItemCategoryDefinition
        //private DestinyDefinitionsDestinyItemCategoryDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyItemCategoryDefinition
            //instance = new DestinyDefinitionsDestinyItemCategoryDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyItemCategoryDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyItemCategoryDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyItemCategoryDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyItemCategoryDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyItemCategoryDefinition");
        }


        /// <summary>
        /// Test the property 'DisplayProperties'
        /// </summary>
        [Test]
        public void DisplayPropertiesTest()
        {
            // TODO unit test for the property 'DisplayProperties'
        }
        /// <summary>
        /// Test the property 'Visible'
        /// </summary>
        [Test]
        public void VisibleTest()
        {
            // TODO unit test for the property 'Visible'
        }
        /// <summary>
        /// Test the property 'ShortTitle'
        /// </summary>
        [Test]
        public void ShortTitleTest()
        {
            // TODO unit test for the property 'ShortTitle'
        }
        /// <summary>
        /// Test the property 'ItemTypeRegex'
        /// </summary>
        [Test]
        public void ItemTypeRegexTest()
        {
            // TODO unit test for the property 'ItemTypeRegex'
        }
        /// <summary>
        /// Test the property 'ItemTypeRegexNot'
        /// </summary>
        [Test]
        public void ItemTypeRegexNotTest()
        {
            // TODO unit test for the property 'ItemTypeRegexNot'
        }
        /// <summary>
        /// Test the property 'OriginBucketIdentifier'
        /// </summary>
        [Test]
        public void OriginBucketIdentifierTest()
        {
            // TODO unit test for the property 'OriginBucketIdentifier'
        }
        /// <summary>
        /// Test the property 'GrantDestinyItemType'
        /// </summary>
        [Test]
        public void GrantDestinyItemTypeTest()
        {
            // TODO unit test for the property 'GrantDestinyItemType'
        }
        /// <summary>
        /// Test the property 'GrantDestinySubType'
        /// </summary>
        [Test]
        public void GrantDestinySubTypeTest()
        {
            // TODO unit test for the property 'GrantDestinySubType'
        }
        /// <summary>
        /// Test the property 'GrantDestinyClass'
        /// </summary>
        [Test]
        public void GrantDestinyClassTest()
        {
            // TODO unit test for the property 'GrantDestinyClass'
        }
        /// <summary>
        /// Test the property 'GroupedCategoryHashes'
        /// </summary>
        [Test]
        public void GroupedCategoryHashesTest()
        {
            // TODO unit test for the property 'GroupedCategoryHashes'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'Redacted'
        /// </summary>
        [Test]
        public void RedactedTest()
        {
            // TODO unit test for the property 'Redacted'
        }

    }

}
