/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyGearArtArrangementReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyGearArtArrangementReferenceTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyGearArtArrangementReference
        //private DestinyDefinitionsDestinyGearArtArrangementReference instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyGearArtArrangementReference
            //instance = new DestinyDefinitionsDestinyGearArtArrangementReference();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyGearArtArrangementReference
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyGearArtArrangementReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyGearArtArrangementReference
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyGearArtArrangementReference> (instance, "variable 'instance' is a DestinyDefinitionsDestinyGearArtArrangementReference");
        }


        /// <summary>
        /// Test the property 'ClassHash'
        /// </summary>
        [Test]
        public void ClassHashTest()
        {
            // TODO unit test for the property 'ClassHash'
        }
        /// <summary>
        /// Test the property 'ArtArrangementHash'
        /// </summary>
        [Test]
        public void ArtArrangementHashTest()
        {
            // TODO unit test for the property 'ArtArrangementHash'
        }

    }

}
