/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyMilestonesDestinyMilestoneActivityPhase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyMilestonesDestinyMilestoneActivityPhaseTests
    {
        // TODO uncomment below to declare an instance variable for DestinyMilestonesDestinyMilestoneActivityPhase
        //private DestinyMilestonesDestinyMilestoneActivityPhase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyMilestonesDestinyMilestoneActivityPhase
            //instance = new DestinyMilestonesDestinyMilestoneActivityPhase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyMilestonesDestinyMilestoneActivityPhase
        /// </summary>
        [Test]
        public void DestinyMilestonesDestinyMilestoneActivityPhaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyMilestonesDestinyMilestoneActivityPhase
            //Assert.IsInstanceOfType<DestinyMilestonesDestinyMilestoneActivityPhase> (instance, "variable 'instance' is a DestinyMilestonesDestinyMilestoneActivityPhase");
        }


        /// <summary>
        /// Test the property 'Complete'
        /// </summary>
        [Test]
        public void CompleteTest()
        {
            // TODO unit test for the property 'Complete'
        }

    }

}
