/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyTalentNodeStepGroups
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyTalentNodeStepGroupsTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyTalentNodeStepGroups
        //private DestinyDefinitionsDestinyTalentNodeStepGroups instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyTalentNodeStepGroups
            //instance = new DestinyDefinitionsDestinyTalentNodeStepGroups();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyTalentNodeStepGroups
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyTalentNodeStepGroupsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyTalentNodeStepGroups
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyTalentNodeStepGroups> (instance, "variable 'instance' is a DestinyDefinitionsDestinyTalentNodeStepGroups");
        }


        /// <summary>
        /// Test the property 'WeaponPerformance'
        /// </summary>
        [Test]
        public void WeaponPerformanceTest()
        {
            // TODO unit test for the property 'WeaponPerformance'
        }
        /// <summary>
        /// Test the property 'ImpactEffects'
        /// </summary>
        [Test]
        public void ImpactEffectsTest()
        {
            // TODO unit test for the property 'ImpactEffects'
        }
        /// <summary>
        /// Test the property 'GuardianAttributes'
        /// </summary>
        [Test]
        public void GuardianAttributesTest()
        {
            // TODO unit test for the property 'GuardianAttributes'
        }
        /// <summary>
        /// Test the property 'LightAbilities'
        /// </summary>
        [Test]
        public void LightAbilitiesTest()
        {
            // TODO unit test for the property 'LightAbilities'
        }
        /// <summary>
        /// Test the property 'DamageTypes'
        /// </summary>
        [Test]
        public void DamageTypesTest()
        {
            // TODO unit test for the property 'DamageTypes'
        }

    }

}
