/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing DestinyDefinitionsDestinyItemSocketBlockDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DestinyDefinitionsDestinyItemSocketBlockDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for DestinyDefinitionsDestinyItemSocketBlockDefinition
        //private DestinyDefinitionsDestinyItemSocketBlockDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DestinyDefinitionsDestinyItemSocketBlockDefinition
            //instance = new DestinyDefinitionsDestinyItemSocketBlockDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DestinyDefinitionsDestinyItemSocketBlockDefinition
        /// </summary>
        [Test]
        public void DestinyDefinitionsDestinyItemSocketBlockDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DestinyDefinitionsDestinyItemSocketBlockDefinition
            //Assert.IsInstanceOfType<DestinyDefinitionsDestinyItemSocketBlockDefinition> (instance, "variable 'instance' is a DestinyDefinitionsDestinyItemSocketBlockDefinition");
        }


        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Test]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }
        /// <summary>
        /// Test the property 'SocketEntries'
        /// </summary>
        [Test]
        public void SocketEntriesTest()
        {
            // TODO unit test for the property 'SocketEntries'
        }
        /// <summary>
        /// Test the property 'SocketCategories'
        /// </summary>
        [Test]
        public void SocketCategoriesTest()
        {
            // TODO unit test for the property 'SocketCategories'
        }

    }

}
