/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing ForumPostResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ForumPostResponseTests
    {
        // TODO uncomment below to declare an instance variable for ForumPostResponse
        //private ForumPostResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ForumPostResponse
            //instance = new ForumPostResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ForumPostResponse
        /// </summary>
        [Test]
        public void ForumPostResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ForumPostResponse
            //Assert.IsInstanceOfType<ForumPostResponse> (instance, "variable 'instance' is a ForumPostResponse");
        }


        /// <summary>
        /// Test the property 'LastReplyTimestamp'
        /// </summary>
        [Test]
        public void LastReplyTimestampTest()
        {
            // TODO unit test for the property 'LastReplyTimestamp'
        }
        /// <summary>
        /// Test the property 'IsPinned'
        /// </summary>
        [Test]
        public void IsPinnedTest()
        {
            // TODO unit test for the property 'IsPinned'
        }
        /// <summary>
        /// Test the property 'UrlMediaType'
        /// </summary>
        [Test]
        public void UrlMediaTypeTest()
        {
            // TODO unit test for the property 'UrlMediaType'
        }
        /// <summary>
        /// Test the property 'Thumbnail'
        /// </summary>
        [Test]
        public void ThumbnailTest()
        {
            // TODO unit test for the property 'Thumbnail'
        }
        /// <summary>
        /// Test the property 'Popularity'
        /// </summary>
        [Test]
        public void PopularityTest()
        {
            // TODO unit test for the property 'Popularity'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Test]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'IsAnnouncement'
        /// </summary>
        [Test]
        public void IsAnnouncementTest()
        {
            // TODO unit test for the property 'IsAnnouncement'
        }
        /// <summary>
        /// Test the property 'UserRating'
        /// </summary>
        [Test]
        public void UserRatingTest()
        {
            // TODO unit test for the property 'UserRating'
        }
        /// <summary>
        /// Test the property 'UserHasRated'
        /// </summary>
        [Test]
        public void UserHasRatedTest()
        {
            // TODO unit test for the property 'UserHasRated'
        }
        /// <summary>
        /// Test the property 'UserHasMutedPost'
        /// </summary>
        [Test]
        public void UserHasMutedPostTest()
        {
            // TODO unit test for the property 'UserHasMutedPost'
        }
        /// <summary>
        /// Test the property 'LatestReplyPostId'
        /// </summary>
        [Test]
        public void LatestReplyPostIdTest()
        {
            // TODO unit test for the property 'LatestReplyPostId'
        }
        /// <summary>
        /// Test the property 'LatestReplyAuthorId'
        /// </summary>
        [Test]
        public void LatestReplyAuthorIdTest()
        {
            // TODO unit test for the property 'LatestReplyAuthorId'
        }
        /// <summary>
        /// Test the property 'IgnoreStatus'
        /// </summary>
        [Test]
        public void IgnoreStatusTest()
        {
            // TODO unit test for the property 'IgnoreStatus'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Test]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

    }

}
