/* 
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.1.1
 * Contact: support@bungie.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BungieNetPlatform.Api;
using BungieNetPlatform.Model;
using BungieNetPlatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BungieNetPlatform.Test
{
    /// <summary>
    ///  Class for testing GroupsV2GroupPotentialMembership
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GroupsV2GroupPotentialMembershipTests
    {
        // TODO uncomment below to declare an instance variable for GroupsV2GroupPotentialMembership
        //private GroupsV2GroupPotentialMembership instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupsV2GroupPotentialMembership
            //instance = new GroupsV2GroupPotentialMembership();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupsV2GroupPotentialMembership
        /// </summary>
        [Test]
        public void GroupsV2GroupPotentialMembershipInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GroupsV2GroupPotentialMembership
            //Assert.IsInstanceOfType<GroupsV2GroupPotentialMembership> (instance, "variable 'instance' is a GroupsV2GroupPotentialMembership");
        }


        /// <summary>
        /// Test the property 'Member'
        /// </summary>
        [Test]
        public void MemberTest()
        {
            // TODO unit test for the property 'Member'
        }
        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Test]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

    }

}
